services:
  cairo:
    container_name: cairo
    build: .
    environment:
      - RUN_SCRIPT=${RUN_SCRIPT:-test}
    env_file:
      - ./.env
    ports:
      - "8100:8100"
    volumes:
      - ./src:/code/src
      - ./build:/code/build
      - ./logs:/code/logs
      - ./.starknet_accounts:/root/.starknet_accounts
      - ./cairo_libs:/code/cairo_libs
      - ./scripts.sh:/code/scripts/scripts.sh
    command: sh -c "chmod +x ./scripts/scripts.sh && ./scripts/run.sh | tee -a ./logs/scripts.log"
volumes:
  logvolume01: {}
